version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "50051:50051"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50051"]
      interval: 5s
      timeout: 3s
      retries: 5

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: ["/client", "-addr", "localhost:50051"]
    network_mode: "host"
    depends_on:
      server:
        condition: service_healthy
